### ISSUE TITLE
Make Library available in Arduino Library Manager

### ISSUE THREAD

**Issue by BrushlessPower** [BrushlessPower/SBUS2-Telemetry#25]
see:

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by ericlangel** [comment]
done 
but not tested yet

**Comment by Troynica** [comment]
Just installed version 1.2.0 through the Library Manager. This works.

**Comment by ericlangel** [comment]
@Troynica Thank you for your comment.
