### ISSUE TITLE
Support Arduino NANO？

### ISSUE THREAD

**Issue by koakumaping** [BrushlessPower/SBUS2-Telemetry#6]
I just had this one.Thanks

**Comment by BrushlessPower** [comment]
There should be no Problem.

Please give a Feedback if it's working or not.

**Comment by koakumaping** [comment]
Thanks.I will try it soon.

**Comment by BrushlessPower** [comment]
It works on a UNO Rev.3
So there should be no Problem with NANO.

Closed, because no answer from koakumaping
